TRIAGE - Feature Request:
  'UP NEXT':
    - 'need specification'
  'IN FUTURE':
    - '0 - Backlog'
  'IN DISCUSSION':
    - 'discussion'

TRIAGE - Bugs:   
   'READY TO WORK ON':
    - '2 - Ready'
    
Feature Specification:
  'PENDING FEATURE REQUEST':
    - '1 - Planning'
    - 'need specification'
  'FEATURE READY':
    - '2 - Ready'
    
DEVELOPMENT CYCLE:
  'TO-DO':
    - '2 - Ready'
  'CODING':
    - '3 - Working'   
  'CODED':
    - 'need tester'
  'FAILED':
    - 'failed :red_circle:'
  'PASSED FUNCTIONAL TEST':
    - 'passed :large_blue_circle:'
  'PULL REQUESTED':
    - '4 - In Review'
    #    'MERGED':

FUNCTIONALITY TEST:
  'TO-DO':
    - 'need tester'
  'IN PROGRESS':
    - '4 - In Review'
  'FAILED': 
    - 'failed :red_circle:' 
  'SUCCESSFUL':
    - 'passed :large_blue_circle:'
