name: labels
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
    paths:
    - '.github/**'

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: sync labels
        uses: tprasadtp/labels@0.3.0+tprasadtp # Use latest version available.
        with:
          owner: "ecureuill" # Optional
          repo: "SELIProject"   # Optional
          # file: "FILENAME"   # Optional
          token: ${{ secrets.GITHUB_TOKEN }}
